[versions]
agp = "8.11.1"
kotlin = "2.2.0"
core-ktx = "1.16.0"
junit = "4.13.2"
espresso-core = "3.7.0"
androidx-test-ext-junit = "1.3.0"
lifecycle-ktx = "2.9.2"
activity-compose = "1.10.1"
compose-bom = "2025.07.00"
material3-compose = "1.3.2"
compose-ui = "1.8.3"
recyclerview = "1.4.0"
datastore = "1.1.7"
gson = "2.13.1"
protobufPlugin = "0.9.5"
protobuf = "4.31.1"
androidx-security = "1.1.0"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-ktx" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle-ktx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose-ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "compose-ui" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose-ui" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose-ui" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose-ui" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "compose-ui" }
material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3-compose" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
datastore = { group = "androidx.datastore", name = "datastore", version.ref = "datastore" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
google-gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson"}
google-protobuf = { group = "com.google.protobuf", name = "protobuf-javalite", version.ref = "protobuf"}
androidx-security-crypto = { group = "androidx.security", name = "security-crypto-ktx", version.ref = "androidx-security"}

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinCompose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinParcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin"}
googleProtobuf = { id = "com.google.protobuf", version.ref = "protobufPlugin"}
